### ISSUE TITLE
gemspec is missing lifecycle_diagram.rb

### ISSUE THREAD

**Issue by 13k** [bryanlarsen/railroad#5]
Gem::Specification.files misses "lib/railroad/lifecycle_diagram.rb"

**Comment by shadowbq** [comment]
<pre>
diff --git a/railroad.gemspec b/railroad.gemspec
index 4ad5c9c..60e43e5 100644
--- a/railroad.gemspec
+++ b/railroad.gemspec
@@ -10,7 +10,7 @@ Gem::Specification.new do |s|
   s.email = "javier@smaldone.com.ar"
   s.executables = ["railroad"]
   s.extra_rdoc_files = ["History.txt", "Manifest.txt", "README.txt"]
-  s.files = ["COPYING", "ChangeLog", "History.txt", "Manifest.txt", "README.txt", "Rakefile", "bin/railroad", "init.rb", "lib/railroad.rb", "lib/railroad/aasm_diagram.rb", "lib/railroad/app_diagram.rb", "lib/railroad/controllers_diagram.rb", "lib/railroad/diagram_graph.rb", "lib/railroad/models_diagram.rb", "lib/railroad/options_struct.rb", "lib/railroad/tasks/diagrams.rb", "lib/railroad/tasks/diagrams.rake"]
+  s.files = ["COPYING", "ChangeLog", "History.txt", "Manifest.txt", "README.txt", "Rakefile", "bin/railroad", "init.rb", "lib/railroad.rb", "lib/railroad/aasm_diagram.rb", "lib/railroad/app_diagram.rb", "lib/railroad/controllers_diagram.rb", "lib/railroad/diagram_graph.rb", "lib/railroad/models_diagram.rb", "lib/railroad/lifecycle_diagram.rb", "lib/railroad/options_struct.rb", "lib/railroad/tasks/diagrams.rb", "lib/railroad/tasks/diagrams.rake"]
   s.has_rdoc = true
   s.homepage = "http://railroad.rubyforge.org"
   s.rdoc_options = ["--main", "README.txt"]
</pre>

**Comment by rnhurt** [comment]
I am seeing this same thing and cannot even run Railroad for my Ruby 1.9.2-p290 / Rails 3.1.0 app.

**Comment by 13k** [comment]
@rnhurt see http://rubygems.org/gems/railroady

**Comment by rnhurt** [comment]
That's a good pointer, 13k.  Thanx!
